---
snacks:
  shortcuts:
    snack: "snack"
    eat: "eat/snack"
    snacks: "snacks"
    store: "store/snack"
    snackhere: "snack/here"
    snackscene: "snack/scene"
    snackmigrate: "snacks/migrate_cookies"

  allow_self_store: true

  snacks:
    bubbly pie:
      aliases: ["bubbly", "bubbly pie", "pie", "bp"]
      give: "gives a warm bubbly pie to"
      eat: "bites into a bubbly pie; hot fruit filling bursts across their tongue."
      desc: "Flaky pie filled with warm, sweet berries."
    meatroll:
      aliases: ["meatroll", "mr"]
      give: "hands over a savory meatroll to"
      eat: "eats a meatroll, the spiced filling warming their belly."
      desc: "Savory roll stuffed with seasoned meat."
    klah:
      aliases: ["klah", "k"]
      give: "offers a steaming mug of klah to"
      eat: "sips the steaming klah, rich and spiced."
      desc: "Rich, spiced hot drink."
    sticky bun:
      aliases: ["sticky bun", "sticky roll", "bun", "sb", "sr"]
      give: "passes a sticky, sweet bun to"
      eat: "takes a sticky bite of a bun, sugar coating their fingers."
      desc: "Sweet bun with cinnamon sugar glaze."
    tea:
      aliases: ["tea", "t"]
      give: "hands over a delicate cup of tea to"
      eat: "sips the tea, feeling the calm of its herbal steam."
      desc: "Soothing herbal beverage."
    wherry stew:
      aliases: ["wherry stew", "ws"]
      give: "lifts a bowl of wherry stew toward"
      eat: "eats a hearty spoon of wherry stew; warmth fills their core."
      desc: "Hearty stew with tender wherry."
    roasted wherry leg:
      aliases: ["roasted wherry leg", "wherry leg", "rwl", "rw"]
      give: "offers a roasted wherry leg to"
      eat: "tears into the roasted wherry leg, juicy meat falling from the bone."
      desc: "Perfectly roasted wherry leg."
    roasted boar:
      aliases: ["roasted boar", "roastedboar", "boar", "rb"]
      give: "presents a slab of roasted boar to"
      eat: "bites into roasted boar, the smoky flavor lingering."
      desc: "Smoky roasted boar meat."
    coffee:
      aliases: ["coffee", "cafe", "c"]
      give: "hands over a steaming cup of coffee to"
      eat: "drinks the strong coffee, feeling alert and focused."
      desc: "Strong, dark-roasted coffee."
    hot chocolate:
      aliases: ["hot chocolate", "hc"]
      give: "passes a mug of hot chocolate to"
      eat: "sips hot chocolate, the creamy sweetness coating the tongue."
      desc: "Creamy, rich hot chocolate."
    zingari whiskey:
      aliases: ["zingari whiskey", "zingari", "whiskey", "zw"]
      give: "slides a small glass of Zingari whiskey toward"
      eat: "takes a fiery swallow of Zingari whiskey; a pleasant haze follows."
      desc: "Potent Zingari whiskey."
    rum:
      aliases: ["rum", "r"]
      give: "offers a shot of rum to"
      eat: "raises a glass of rum and savors the smooth burn."
      desc: "Smooth amber rum."
    benden wine:
      aliases: ["benden wine", "bw"]
      give: "hands over a goblet of Benden wine to"
      eat: "sips Benden wine; sun-warmed grapes linger on the palate."
      desc: "Velvety Benden red wine."
    deleri wine:
      aliases: ["deleri wine", "deleri", "dw"]
      give: "presents a delicate glass of Deleri wine to"
      eat: "sips the delicate Deleri wine. A warm euphoria spreads through you as visions of tiny pink and purple firelizards swirl and dance about your head."
      desc: "Delicate Deleri wine with a dreamy finish."
    turnover cookies:
      aliases: ["turnover cookies", "cookies", "tc"]
      give: "passes a crisp turnover cookie to"
      eat: "eats a turnover cookie; flaky pastry and sweet jam bring fond memories."
      desc: "Crisp cookies with jam filling."
